# Generated by Django 6.0.4 on 2026-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('concluido', 'Concluído')], default='recebido', max_length=20),
        ),
    ]
